from .creature import Creature
from .basilisk import Basilisk
from .bigfoot import Bigfoot
from .cthulhu import Cthulhu
from .dragon import Dragon
from .griffin import Griffin
from .kraken import Kraken
from .loch_ness import Loch_Ness
from .megalodon import Megalodon
from .pterodactyl import Pterodactyl
from .raptor import Raptor
from .t_rex import T_Rex
from .vampire import Vampire
from .werewolf import Werewolf
from .yeti import Yeti
from .zapdos import Zapdos
